<?php
require("logoutmodal.php");
require("addnewadmin.php");
require("removeuser.php");
require("rmadminModal.php");
require("profilemodal.php");
require("addfeaturedproduct.php");
require("edit.php");
?>