// contains errors
var err = ['Failed To get Category Info!',
    'Failed To get User Info!',
    'Please Enter Location',
    'User Name is invalid. It must contain 3 to 15 characters.',
    'User Email Input is Invalid. It should be like example@domain.com',
    'User Contact Input is Invalid. It should be 10 digits',
    'Please Select an option from dropdown!',
    'Please Enter Cost!',
    'Please Enter Title for Ad!',
    'Please Select Type of User!',
    'Company name is required!',
    'Company email is required!',
    'Company Contact is required!',
    'Please select Advertisement Type!',
    'Please select Paid Advertisement Type!',
    'Please Select your Option Buy/Sell!',
    'Please Enter Bike Brand Name!',
    'Please Specify registration year of Bike!',
    'Please Specify Kms travelled on Bike!',
    'Please Enter Some Description!',
    'Please Enter Car Brand Name!',
    'Please Specify registration year of Car!',
    'Please Specify Kms travelled on Car!',
    'Please Specify Other!',
    'Please Enter Value in Fee Column!',
    'Please Specify the target stream!',
    'Please Enter Institute Name!',
    'Please Enter Institute Address!',
    'Please Select What you want to do!',
    'Please Select your choice of Area!',
    'Please Select Job Type',
    'Please Mention role',
    'Please mention Minimum salary',
    'Please mention Maximum salary',
    'Please enter Experience Required',
    'Invalid Recruiter Contact Number',
    'Select A subcategory',
    'Please Select Condition',
    'Please Mention How long its been used',
    'Please select Bill Option',
    'Please Enter Brand',
    'Please Enter Model',
    'Write what package includes',
    'Failed to Perform Operation! Try Again',
    'Wrong Choice',
    'Please Select an Event Type first',
    'Please Enter Location of Event',
    'Please Select Service type',
    'Invalid Contact',
    'Invalid Email',
    'Invalid Name',
    'Please Select a category First'];